services:
    postgres-db:
        image: postgres:15-alpine
        container_name: postgres_container
        environment:
            POSTGRES_DB: agenda
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: its2004fj5
        ports:
            -"5432:5432"
            
