spring.application.name=agenda

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:agenda}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:B4lenci@ga}
spring.jpa.hibernate.ddl-auto=update