version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: postgres_springboot
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: its2004fj5
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postresql/data

volumes:
  postgres_data: